on:
  workflow_call:
    inputs:
      btp-subdomain:
        type: string
        required: false
        default: 2e7eb2c6trial
      btp-subaccount-id:
        type: string
        required: false
        default: eade3b00-2c92-4e94-b7f0-6ab3d16a0da8
      cf-api:
        type: string
        required: false
        default: 'https://api.cf.us10-001.hana.ondemand.com'
      cf-org:
        type: string
        required: false
        default: 2e7eb2c6trial
      cf-space:
        type: string
        required: true
      role-collection:
        type: string
        required: true
      mta-source-dir:
        description: relative path to dir with mta.yaml
        type: string
        required: false
        default: '.'
      mtar-dir:
        description: path to dir with mtar
        type: string
        required: false
        default: mta_archives
      mtar-file:
        description: file name of mtar
        type: string
        required: false
        default: cap-ui5-standalone.mtar
    secrets:
      username:
        required: true
      password:
        required: true
      grant-users:
        description: List of users to assign the role role-collection to
        required: false
    outputs:
      ui_app_url:
        value: ${{ jobs.deployment.outputs.ui_app_url }}

jobs:
  deployment:
    name: To BTP
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.url }}
    concurrency: staging
    env:
      CF_API: ${{ inputs.cf-api }}
      CF_ORG: ${{ inputs.cf-org }}
      CF_SPACE: ${{ inputs.cf-space }}
      CF_USERNAME: ${{ secrets.username }}
      CF_PASSWORD: ${{ secrets.password }}
      GRANT_USERS: ${{ secrets.grant-users }}
    outputs:
      ui_app_url: ${{ steps.deploy.outputs.url }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - uses: actions/cache@v4
      id: cache
      with:
        path: ${{ inputs.mtar-dir }}/${{ inputs.mtar-file }}
        key: ${{ runner.os }}-${{ github.head_ref || github.ref_name }}-${{ hashFiles('_i18n/**','app/**','db/**','srv/**','*.json','**/mta.yaml') }}

    - name: Install MBT
      run: npm install -g mbt

    - name: MTA build
      if: steps.cache.outputs.cache-hit != 'true'
      run: mbt build -s ${{ inputs.mta-source-dir }} -t ${{ inputs.mtar-dir }} --mtar ${{ inputs.mtar-file }}

    - name: CF Deploy
      id: deploy
      uses: ./.github/actions/cf-deploy
      with:
        createspace: true
        mtafile: ${{ inputs.mtar-dir }}/${{ inputs.mtar-file }}
        findurl_command: 'cf apps | grep cap-ui5-standalone | awk "{print \$6}"' 